In [1]:
import utils

/home/bchnge/anaconda3/lib/python3.6/site-packages/ggplot/utils.py:81: FutureWarning: pandas.tslib is deprecated and will be removed in a future version.
You can access Timestamp as pandas.Timestamp
  pd.tslib.Timestamp,
/home/bchnge/anaconda3/lib/python3.6/site-packages/ggplot/stats/smoothers.py:4: FutureWarning: The pandas.lib module is deprecated and will be removed in a future version. These are private functions and can be accessed from pandas._libs.lib instead
  from pandas.lib import Timestamp
/home/bchnge/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

In [7]:
import pandas as pd
import os
import random
import numpy as np
from pprint import pprint

%matplotlib inline

In [9]:
data_path = '/vol2/competitions/home-credit-default-risk/'
data_files =  [data_path + x for x in os.listdir(data_path)]

In [3]:
df = utils.load_data()

In [5]:
id_target = df[['SK_ID_CURR','TARGET']]

In [16]:
a = pd.read_csv(data_path + 'previous_application.csv.zip').merge(id_target, how = 'inner', on = 'SK_ID_CURR')

In [22]:
from sklearn.ensemble import RandomForestClassifier

In [24]:
a.columns

Index(['SK_ID_PREV', 'SK_ID_CURR', 'NAME_CONTRACT_TYPE', 'AMT_ANNUITY',
       'AMT_APPLICATION', 'AMT_CREDIT', 'AMT_DOWN_PAYMENT', 'AMT_GOODS_PRICE',
       'WEEKDAY_APPR_PROCESS_START', 'HOUR_APPR_PROCESS_START',
       'FLAG_LAST_APPL_PER_CONTRACT', 'NFLAG_LAST_APPL_IN_DAY',
       'RATE_DOWN_PAYMENT', 'RATE_INTEREST_PRIMARY',
       'RATE_INTEREST_PRIVILEGED', 'NAME_CASH_LOAN_PURPOSE',
       'NAME_CONTRACT_STATUS', 'DAYS_DECISION', 'NAME_PAYMENT_TYPE',
       'CODE_REJECT_REASON', 'NAME_TYPE_SUITE', 'NAME_CLIENT_TYPE',
       'NAME_GOODS_CATEGORY', 'NAME_PORTFOLIO', 'NAME_PRODUCT_TYPE',
       'CHANNEL_TYPE', 'SELLERPLACE_AREA', 'NAME_SELLER_INDUSTRY',
       'CNT_PAYMENT', 'NAME_YIELD_GROUP', 'PRODUCT_COMBINATION',
       'DAYS_FIRST_DRAWING', 'DAYS_FIRST_DUE', 'DAYS_LAST_DUE_1ST_VERSION',
       'DAYS_LAST_DUE', 'DAYS_TERMINATION', 'NFLAG_INSURED_ON_APPROVAL',
       'TARGET'],
      dtype='object')

In [ ]:
rf = RandomForestClassifier(n_jobs=3).fit()

In [30]:
a['application_index'] = a.groupby('SK_ID_CURR').cumcount()+1

In [40]:
a.groupby('CODE_REJECT_REASON')['TARGET'].mean()

CODE_REJECT_REASON
CLIENT    0.082517
HC        0.117342
LIMIT     0.125594
SCO       0.099982
SCOFR     0.209287
SYSTEM    0.062500
VERIF     0.092563
XAP       0.079477
XNA       0.100959
Name: TARGET, dtype: float64

In [42]:
b = ['a','b','c']

In [44]:
b

['a', 'c']

In [77]:
f = list(a.columns)
f.remove('SK_ID_CURR')
f.remove('SK_ID_PREV')
f.remove('TARGET')

In [78]:
X1, y1 = utils.get_design_matrix(a, features = f)

In [79]:
X2 = X1.dropna()
y2 = y1[X2.index]

In [190]:
def get_design_matrix_refined(data, features, train_test_split = False, train_sample = 0.75):
    objects = data.columns[(data.dtypes == object)]
    objects = objects[objects.isin(features)]

    numerics = data.columns[(data.dtypes != object)]
    numerics = numerics[numerics.isin(features)]
    
    data = data[features + ['TARGET']]
    
    # Convert categorical to dummy
    for o in objects:
        data = pd.concat([data, pd.get_dummies(data[o], prefix = o, prefix_sep = '_')], axis = 1)
        del data[o]                

    # Discretize numerics if needed
    for n in numerics:
        if pd.isnull(data[n]).sum() > 0:
            data[n] = data[n]
            disc = pd.qcut(data[n], q = 100, duplicates = 'drop')
            print(disc.head())
            disc_dummies = pd.get_dummies(disc, prefix = n, prefix_sep = '_', dummy_na= True)
            print(disc_dummies.head())
            data = pd.concat([data, disc_dummies], axis = 1)
            del data[n]
        
    train_sample_idx = np.array([random.random() <= train_sample for i in range(data.shape[0])])
    
    if train_test_split:
        X_train = data.loc[train_sample_idx].drop('TARGET', axis = 1)
        y_train = data.loc[train_sample_idx, 'TARGET']
        X_test = data.loc[~train_sample_idx].drop('TARGET', axis = 1)
        y_test = data.loc[~train_sample_idx, 'TARGET']
        return(X_train, y_train, X_test, y_test)
    else:
        X = data.drop('TARGET', axis = 1)
        y = data['TARGET']
        return(X, y)

In [191]:
X3, y3 = get_design_matrix_refined(a, features = f)

0        (-0.001, 2130.562]
1    (58205.475, 69364.215]
2     (12309.993, 12586.86]
3     (25080.93, 25957.395]
4       (21131.73, 21826.8]
Name: AMT_ANNUITY, dtype: category
Categories (99, interval[float64]): [(-0.001, 2130.562] < (2130.562, 2250.0] < (2250.0, 2396.79] < (2396.79, 2731.05] ... (48255.525, 52481.147] < (52481.147, 58205.475] < (58205.475, 69364.215] < (69364.215, 418058.145]]
   AMT_ANNUITY_(-0.001, 2130.562]  AMT_ANNUITY_(2130.562, 2250.0]  \
0                               1                               0
1                               0                               0
2                               0                               0
3                               0                               0
4                               0                               0

   AMT_ANNUITY_(2250.0, 2396.79]  AMT_ANNUITY_(2396.79, 2731.05]  \
0                              0                               0
1                              0                               0
2                              0                               0
3                              0                               0
4                              0                               0

   AMT_ANNUITY_(2731.05, 2984.441]  AMT_ANNUITY_(2984.441, 3214.395]  \
0                                0                                 0
1                                0                                 0
2                                0                                 0
3                                0                                 0
4                                0                                 0

   AMT_ANNUITY_(3214.395, 3375.0]  AMT_ANNUITY_(3375.0, 3577.365]  \
0                               0                               0
1                               0                               0
2                               0                               0
3                               0                               0
4                               0                               0

   AMT_ANNUITY_(3577.365, 3790.989]  AMT_ANNUITY_(3790.989, 3976.56]  \
0                                 0                                0
1                                 0                                0
2                                 0                                0
3                                 0                                0
4                                 0                                0

        ...         AMT_ANNUITY_(36199.8, 38250.0]  \
0       ...                                      0
1       ...                                      0
2       ...                                      0
3       ...                                      0
4       ...                                      0

   AMT_ANNUITY_(38250.0, 40196.768]  AMT_ANNUITY_(40196.768, 42841.8]  \
0                                 0                                 0
1                                 0                                 0
2                                 0                                 0
3                                 0                                 0
4                                 0                                 0

   AMT_ANNUITY_(42841.8, 45205.605]  AMT_ANNUITY_(45205.605, 48255.525]  \
0                                 0                                   0
1                                 0                                   0
2                                 0                                   0
3                                 0                                   0
4                                 0                                   0

   AMT_ANNUITY_(48255.525, 52481.147]  AMT_ANNUITY_(52481.147, 58205.475]  \
0                                   0                                   0
1                                   0                                   0
2                                   0                                   0
3                                   0                                   0
4                                   0                                   0

   AMT_ANNUITY_(58205.475, 69364.215]  AMT_ANNUITY_(69364.215, 418058.145]  \
0                                   0                                    0
1                                   1                                    0
2                                   0                                    0
3                                   0                                    0
4                                   0                                    0

   AMT_ANNUITY_nan
0                0
1                0
2                0
3                0
4                0

[5 rows x 100 columns]
0        (17059.5, 19278.0]
1    (1515415.5, 4509688.5]
2    (115822.8, 120048.255]
3      (653706.0, 721332.0]
4      (495000.0, 533160.0]
Name: AMT_CREDIT, dtype: category
Categories (80, interval[float64]): [(-0.001, 14593.5] < (14593.5, 17059.5] < (17059.5, 19278.0] < (19278.0, 21253.5] ... (978408.0, 1125000.0] < (1125000.0, 1293502.5] < (1293502.5, 1515415.5] < (1515415.5, 4509688.5]]
   AMT_CREDIT_(-0.001, 14593.5]  AMT_CREDIT_(14593.5, 17059.5]  \
0                             0                              0
1                             0                              0
2                             0                              0
3                             0                              0
4                             0                              0

   AMT_CREDIT_(17059.5, 19278.0]  AMT_CREDIT_(19278.0, 21253.5]  \
0                              1                              0
1                              0                              0
2                              0                              0
3                              0                              0
4                              0                              0

   AMT_CREDIT_(21253.5, 23094.0]  AMT_CREDIT_(23094.0, 24880.5]  \
0                              0                              0
1                              0                              0
2                              0                              0
3                              0                              0
4                              0                              0

   AMT_CREDIT_(24880.5, 26685.0]  AMT_CREDIT_(26685.0, 28476.0]  \
0                              0                              0
1                              0                              0
2                              0                              0
3                              0                              0
4                              0                              0

   AMT_CREDIT_(28476.0, 30379.5]  AMT_CREDIT_(30379.5, 32319.0]  \
0                              0                              0
1                              0                              0
2                              0                              0
3                              0                              0
4                              0                              0

        ...        AMT_CREDIT_(573408.0, 653706.0]  \
0       ...                                      0
1       ...                                      0
2       ...                                      0
3       ...                                      0
4       ...                                      0

   AMT_CREDIT_(653706.0, 721332.0]  AMT_CREDIT_(721332.0, 769419.0]  \
0                                0                                0
1                                0                                0
2                                0                                0
3                                1                                0
4                                0                                0

   AMT_CREDIT_(769419.0, 893398.5]  AMT_CREDIT_(893398.5, 978408.0]  \
0                                0                                0
1                                0                                0
2                                0                                0
3                                0                                0
4                                0                                0

   AMT_CREDIT_(978408.0, 1125000.0]  AMT_CREDIT_(1125000.0, 1293502.5]  \
0                                 0                                  0
1                                 0                                  0
2                                 0                                  0
3                                 0                                  0
4                                 0                                  0

   AMT_CREDIT_(1293502.5, 1515415.5]  AMT_CREDIT_(1515415.5, 4509688.5]  \
0                                  0                                  0
1                                  0                                  1
2                                  0                                  0
3                                  0                                  0
4                                  0                                  0

   AMT_CREDIT_nan
0               0
1               0
2               0
3               0
4               0

[5 rows x 81 columns]
0           (-0.901, 0.0]
1    (64222.2, 3060045.0]
2           (-0.901, 0.0]
3                     NaN
4                     NaN
Name: AMT_DOWN_PAYMENT, dtype: category
Categories (50, interval[float64]): [(-0.901, 0.0] < (0.0, 3.105] < (3.105, 1417.5] < (1417.5, 1791.0] ... (29700.0, 36000.0] < (36000.0, 45000.0] < (45000.0, 64222.2] < (64222.2, 3060045.0]]
   AMT_DOWN_PAYMENT_(-0.901, 0.0]  AMT_DOWN_PAYMENT_(0.0, 3.105]  \
0                               1                              0
1                               0                              0
2                               1                              0
3                               0                              0
4                               0                              0

   AMT_DOWN_PAYMENT_(3.105, 1417.5]  AMT_DOWN_PAYMENT_(1417.5, 1791.0]  \
0                                 0                                  0
1                                 0                                  0
2                                 0                                  0
3                                 0                                  0
4                                 0                                  0

   AMT_DOWN_PAYMENT_(1791.0, 2025.0]  AMT_DOWN_PAYMENT_(2025.0, 2250.0]  \
0                                  0                                  0
1                                  0                                  0
2                                  0                                  0
3                                  0                                  0
4                                  0                                  0

   AMT_DOWN_PAYMENT_(2250.0, 2340.0]  AMT_DOWN_PAYMENT_(2340.0, 2556.0]  \
0                                  0                                  0
1                                  0                                  0
2                                  0                                  0
3                                  0                                  0
4                                  0                                  0

   AMT_DOWN_PAYMENT_(2556.0, 2700.0]  AMT_DOWN_PAYMENT_(2700.0, 2934.0]  \
0                                  0                                  0
1                                  0                                  0
2                                  0                                  0
3                                  0                                  0
4                                  0                                  0

           ...           AMT_DOWN_PAYMENT_(18000.0, 19800.0]  \
0          ...                                             0
1          ...                                             0
2          ...                                             0
3          ...                                             0
4          ...                                             0

   AMT_DOWN_PAYMENT_(19800.0, 22491.0]  AMT_DOWN_PAYMENT_(22491.0, 22500.0]  \
0                                    0                                    0
1                                    0                                    0
2                                    0                                    0
3                                    0                                    0
4                                    0                                    0

   AMT_DOWN_PAYMENT_(22500.0, 25740.0]  AMT_DOWN_PAYMENT_(25740.0, 29700.0]  \
0                                    0                                    0
1                                    0                                    0
2                                    0                                    0
3                                    0                                    0
4                                    0                                    0

   AMT_DOWN_PAYMENT_(29700.0, 36000.0]  AMT_DOWN_PAYMENT_(36000.0, 45000.0]  \
0                                    0                                    0
1                                    0                                    0
2                                    0                                    0
3                                    0                                    0
4                                    0                                    0

   AMT_DOWN_PAYMENT_(45000.0, 64222.2]  AMT_DOWN_PAYMENT_(64222.2, 3060045.0]  \
0                                    0                                      0
1                                    0                                      1
2                                    0                                      0
3                                    0                                      0
4                                    0                                      0

   AMT_DOWN_PAYMENT_nan
0                     0
1                     0
2                     0
3                     1
4                     1

[5 rows x 51 columns]
0      (15299.629, 17730.0]
1    (1395000.0, 5850000.0]
2      (106186.5, 110245.5]
3      (585000.0, 675000.0]
4      (423225.0, 450000.0]
Name: AMT_GOODS_PRICE, dtype: category
Categories (86, interval[float64]): [(-0.001, 15299.629] < (15299.629, 17730.0] < (17730.0, 19530.0] < (19530.0, 21240.0] ... (1035000.0, 1129500.0] < (1129500.0, 1305000.0] < (1305000.0, 1395000.0] < (1395000.0, 5850000.0]]
   AMT_GOODS_PRICE_(-0.001, 15299.629]  AMT_GOODS_PRICE_(15299.629, 17730.0]  \
0                                    0                                     1
1                                    0                                     0
2                                    0                                     0
3                                    0                                     0
4                                    0                                     0

   AMT_GOODS_PRICE_(17730.0, 19530.0]  AMT_GOODS_PRICE_(19530.0, 21240.0]  \
0                                   0                                   0
1                                   0                                   0
2                                   0                                   0
3                                   0                                   0
4                                   0                                   0

   AMT_GOODS_PRICE_(21240.0, 22590.0]  AMT_GOODS_PRICE_(22590.0, 24259.23]  \
0                                   0                                    0
1                                   0                                    0
2                                   0                                    0
3                                   0                                    0
4                                   0                                    0

   AMT_GOODS_PRICE_(24259.23, 25695.0]  AMT_GOODS_PRICE_(25695.0, 26995.5]  \
0                                    0                                   0
1                                    0                                   0
2                                    0                                   0
3                                    0                                   0
4                                    0                                   0

   AMT_GOODS_PRICE_(26995.5, 28728.0]  AMT_GOODS_PRICE_(28728.0, 30140.55]  \
0                                   0                                    0
1                                   0                                    0
2                                   0                                    0
3                                   0                                    0
4                                   0                                    0

          ...           AMT_GOODS_PRICE_(585000.0, 675000.0]  \
0         ...                                              0
1         ...                                              0
2         ...                                              0
3         ...                                              1
4         ...                                              0

   AMT_GOODS_PRICE_(675000.0, 760500.0]  AMT_GOODS_PRICE_(760500.0, 855000.0]  \
0                                     0                                     0
1                                     0                                     0
2                                     0                                     0
3                                     0                                     0
4                                     0                                     0

   AMT_GOODS_PRICE_(855000.0, 900000.0]  \
0                                     0
1                                     0
2                                     0
3                                     0
4                                     0

   AMT_GOODS_PRICE_(900000.0, 1035000.0]  \
0                                      0
1                                      0
2                                      0
3                                      0
4                                      0

   AMT_GOODS_PRICE_(1035000.0, 1129500.0]  \
0                                       0
1                                       0
2                                       0
3                                       0
4                                       0

   AMT_GOODS_PRICE_(1129500.0, 1305000.0]  \
0                                       0
1                                       0
2                                       0
3                                       0
4                                       0

   AMT_GOODS_PRICE_(1305000.0, 1395000.0]  \
0                                       0
1                                       0
2                                       0
3                                       0
4                                       0

   AMT_GOODS_PRICE_(1395000.0, 5850000.0]  AMT_GOODS_PRICE_nan
0                                       0                    0
1                                       1                    0
2                                       0                    0
3                                       0                    0
4                                       0                    0

[5 rows x 87 columns]
0     (-1.59788e-05, 0.0]
1    (0.101209, 0.101383]
2     (-1.59788e-05, 0.0]
3                     NaN
4                     NaN
Name: RATE_DOWN_PAYMENT, dtype: category
Categories (51, interval[float64]): [(-1.59788e-05, 0.0] < (0.0, 3.1545e-05] < (3.1545e-05, 0.0479757] < (0.0479757, 0.0624893] ... (0.31862, 0.358831] < (0.358831, 0.423146] < (0.423146, 0.521604] < (0.521604, 1.0]]
   RATE_DOWN_PAYMENT_(-1.59788e-05, 0.0]  RATE_DOWN_PAYMENT_(0.0, 3.1545e-05]  \
0                                      1                                    0
1                                      0                                    0
2                                      1                                    0
3                                      0                                    0

In [194]:
rf = RandomForestClassifier(n_jobs = 3)

In [ ]:
rf.fit(X3, y3)

In [197]:
feature_importances = dict([(X3.columns[i], fi) for i,fi in enumerate( rf.feature_importances_)])

In [213]:
feature_importances_df= pd.DataFrame.from_dict(feature_importances, orient = 'index').rename(columns = {0:'fi'}).assign(feature = lambda x: x.index)

In [214]:
feature_importances_df

,fi,feature
AMT_APPLICATION,0.031119,AMT_APPLICATION
HOUR_APPR_PROCESS_START,0.071316,HOUR_APPR_PROCESS_START
NFLAG_LAST_APPL_IN_DAY,0.000311,NFLAG_LAST_APPL_IN_DAY
DAYS_DECISION,0.206531,DAYS_DECISION
SELLERPLACE_AREA,0.032550,SELLERPLACE_AREA
application_index,0.075162,application_index
NAME_CONTRACT_TYPE_Cash loans,0.000206,NAME_CONTRACT_TYPE_Cash loans
NAME_CONTRACT_TYPE_Consumer loans,0.000224,NAME_CONTRACT_TYPE_Consumer loans
NAME_CONTRACT_TYPE_Revolving loans,0.000101,NAME_CONTRACT_TYPE_Revolving loans
NAME_CONTRACT_TYPE_XNA,0.000017,NAME_CONTRACT_TYPE_XNA
WEEKDAY_APPR_PROCESS_START_FRIDAY,0.008953,WEEKDAY_APPR_PROCESS_START_FRIDAY
WEEKDAY_APPR_PROCESS_START_MONDAY,0.008986,WEEKDAY_APPR_PROCESS_START_MONDAY
WEEKDAY_APPR_PROCESS_START_SATURDAY,0.008261,WEEKDAY_APPR_PROCESS_START_SATURDAY
WEEKDAY_APPR_PROCESS_START_SUNDAY,0.006234,WEEKDAY_APPR_PROCESS_START_SUNDAY
WEEKDAY_APPR_PROCESS_START_THURSDAY,0.008647,WEEKDAY_APPR_PROCESS_START_THURSDAY
WEEKDAY_APPR_PROCESS_START_TUESDAY,0.008710,WEEKDAY_APPR_PROCESS_START_TUESDAY
WEEKDAY_APPR_PROCESS_START_WEDNESDAY,0.008882,WEEKDAY_APPR_PROCESS_START_WEDNESDAY
FLAG_LAST_APPL_PER_CONTRACT_N,0.000232,FLAG_LAST_APPL_PER_CONTRACT_N
FLAG_LAST_APPL_PER_CONTRACT_Y,0.000249,FLAG_LAST_APPL_PER_CONTRACT_Y
NAME_CASH_LOAN_PURPOSE_Building a house or an annex,0.000335,NAME_CASH_LOAN_PURPOSE_Building a house or an ...
NAME_CASH_LOAN_PURPOSE_Business development,0.000085,NAME_CASH_LOAN_PURPOSE_Business development
NAME_CASH_LOAN_PURPOSE_Buying a garage,0.000026,NAME_CASH_LOAN_PURPOSE_Buying a garage
NAME_CASH_LOAN_PURPOSE_Buying a holiday home / land,0.000094,NAME_CASH_LOAN_PURPOSE_Buying a holiday home /...
NAME_CASH_LOAN_PURPOSE_Buying a home,0.000151,NAME_CASH_LOAN_PURPOSE_Buying a home
NAME_CASH_LOAN_PURPOSE_Buying a new car,0.000100,NAME_CASH_LOAN_PURPOSE_Buying a new car
NAME_CASH_LOAN_PURPOSE_Buying a used car,0.000335,NAME_CASH_LOAN_PURPOSE_Buying a used car
NAME_CASH_LOAN_PURPOSE_Car repairs,0.000174,NAME_CASH_LOAN_PURPOSE_Car repairs
NAME_CASH_LOAN_PURPOSE_Education,0.000189,NAME_CASH_LOAN_PURPOSE_Education
NAME_CASH_LOAN_PURPOSE_Everyday expenses,0.000266,NAME_CASH_LOAN_PURPOSE_Everyday expenses
NAME_CASH_LOAN_PURPOSE_Furniture,0.000141,NAME_CASH_LOAN_PURPOSE_Furniture
...,...,...
"DAYS_TERMINATION_(-473.0, -451.0]",0.000558,"DAYS_TERMINATION_(-473.0, -451.0]"
"DAYS_TERMINATION_(-451.0, -429.0]",0.000530,"DAYS_TERMINATION_(-451.0, -429.0]"
"DAYS_TERMINATION_(-429.0, -408.0]",0.000498,"DAYS_TERMINATION_(-429.0, -408.0]"
"DAYS_TERMINATION_(-408.0, -389.0]",0.000520,"DAYS_TERMINATION_(-408.0, -389.0]"
"DAYS_TERMINATION_(-389.0, -369.0]",0.000540,"DAYS_TERMINATION_(-389.0, -369.0]"
"DAYS_TERMINATION_(-369.0, -351.0]",0.000531,"DAYS_TERMINATION_(-369.0, -351.0]"
"DAYS_TERMINATION_(-351.0, -332.0]",0.000555,"DAYS_TERMINATION_(-351.0, -332.0]"
"DAYS_TERMINATION_(-332.0, -313.0]",0.000587,"DAYS_TERMINATION_(-332.0, -313.0]"
"DAYS_TERMINATION_(-313.0, -297.0]",0.000506,"DAYS_TERMINATION_(-313.0, -297.0]"
"DAYS_TERMINATION_(-297.0, -279.0]",0.000571,"DAYS_TERMINATION_(-297.0, -279.0]"
"DAYS_TERMINATION_(-279.0, -262.0]",0.000559,"DAYS_TERMINATION_(-279.0, -262.0]"
"DAYS_TERMINATION_(-262.0, -245.0]",0.000556,"DAYS_TERMINATION_(-262.0, -245.0]"
"DAYS_TERMINATION_(-245.0, -228.0]",0.000546,"DAYS_TERMINATION_(-245.0, -228.0]"
"DAYS_TERMINATION_(-228.0, -212.0]",0.000589,"DAYS_TERMINATION_(-228.0, -212.0]"
"DAYS_TERMINATION_(-212.0, -195.0]",0.000574,"DAYS_TERMINATION_(-212.0, -195.0]"
"DAYS_TERMINATION_(-195.0, -178.0]",0.000598,"DAYS_TERMINATION_(-195.0, -178.0]"
"DAYS_TERMINATION_(-178.0, -162.0]",0.000599,"DAYS_TERMINATION_(-178.0, -162.0]"
"DAYS_TERMINATION_(-162.0, -145.0]",0.000579,"DAYS_TERMINATION_(-162.0, -145.0]"
"DAYS_TERMINATION_(-145.0, -128.0]",0.000547,"DAYS_TERMINATION_(-145.0, -128.0]"
"DAYS_TERMINATION_(-128.0, -111.0]",0.000551,"DAYS_TERMINATION_(-128.0, -111.0]"
"DAYS_TERMINATION_(-111.0, -94.0]",0.000549,"DAYS_TERMINATION_(-111.0, -94.0]"
"DAYS_TERMINATION_(-94.0, -77.0]",0.000478,"DAYS_TERMINATION_(-94.0, -77.0]"
"DAYS_TERMINATION_(-77.0, -60.0]",0.000474,"DAYS_TERMINATION_(-77.0, -60.0]"
"DAYS_TERMINATION_(-60.0, -42.0]",0.000530,"DAYS_TERMINATION_(-60.0, -42.0]"
"DAYS_TERMINATION_(-42.0, -24.0]",0.000520,"DAYS_TERMINATION_(-42.0, -24.0]"
"DAYS_TERMINATION_(-24.0, -6.0]",0.000472,"DAYS_TERMINATION_(-24.0, -6.0]"
"DAYS_TERMINATION_(-6.0, 365243.0]",0.001845,"DAYS_TERMINATION_(-6.0, 365243.0]"
DAYS_TERMINATION_nan,0.000166,DAYS_TERMINATION_nan
"NFLAG_INSURED_ON_APPROVAL_(-0.001, 1.0]",0.000387,"NFLAG_INSURED_ON_APPROVAL_(-0.001, 1.0]"
NFLAG_INSURED_ON_APPROVAL_nan,0.000240,NFLAG_INSURED_ON_APPROVAL_nan

In [219]:
from ggplot import ggplot, aes, geom_bar, geom_point

In [224]:
feature_importances_df.sort_values(by = 'fi', ascending = False)

,fi,feature
DAYS_DECISION,0.206531,DAYS_DECISION
application_index,0.075162,application_index
HOUR_APPR_PROCESS_START,0.071316,HOUR_APPR_PROCESS_START
SELLERPLACE_AREA,0.032550,SELLERPLACE_AREA
AMT_APPLICATION,0.031119,AMT_APPLICATION
WEEKDAY_APPR_PROCESS_START_MONDAY,0.008986,WEEKDAY_APPR_PROCESS_START_MONDAY
WEEKDAY_APPR_PROCESS_START_FRIDAY,0.008953,WEEKDAY_APPR_PROCESS_START_FRIDAY
WEEKDAY_APPR_PROCESS_START_WEDNESDAY,0.008882,WEEKDAY_APPR_PROCESS_START_WEDNESDAY
WEEKDAY_APPR_PROCESS_START_TUESDAY,0.008710,WEEKDAY_APPR_PROCESS_START_TUESDAY
WEEKDAY_APPR_PROCESS_START_THURSDAY,0.008647,WEEKDAY_APPR_PROCESS_START_THURSDAY
NAME_TYPE_SUITE_Unaccompanied,0.008624,NAME_TYPE_SUITE_Unaccompanied
WEEKDAY_APPR_PROCESS_START_SATURDAY,0.008261,WEEKDAY_APPR_PROCESS_START_SATURDAY
WEEKDAY_APPR_PROCESS_START_SUNDAY,0.006234,WEEKDAY_APPR_PROCESS_START_SUNDAY
NAME_TYPE_SUITE_Family,0.005440,NAME_TYPE_SUITE_Family
NAME_CLIENT_TYPE_Repeater,0.005325,NAME_CLIENT_TYPE_Repeater
CHANNEL_TYPE_Country-wide,0.003995,CHANNEL_TYPE_Country-wide
"CNT_PAYMENT_(10.0, 12.0]",0.003870,"CNT_PAYMENT_(10.0, 12.0]"
NAME_CLIENT_TYPE_Refreshed,0.003833,NAME_CLIENT_TYPE_Refreshed
NAME_PAYMENT_TYPE_Cash through the bank,0.003549,NAME_PAYMENT_TYPE_Cash through the bank
NAME_PAYMENT_TYPE_XNA,0.003226,NAME_PAYMENT_TYPE_XNA
NAME_CLIENT_TYPE_New,0.003208,NAME_CLIENT_TYPE_New
"NAME_TYPE_SUITE_Spouse, partner",0.003081,"NAME_TYPE_SUITE_Spouse, partner"
CHANNEL_TYPE_Stone,0.003076,CHANNEL_TYPE_Stone
"CNT_PAYMENT_(20.0, 24.0]",0.002631,"CNT_PAYMENT_(20.0, 24.0]"
CODE_REJECT_REASON_HC,0.002590,CODE_REJECT_REASON_HC
CHANNEL_TYPE_Regional / Local,0.002563,CHANNEL_TYPE_Regional / Local
NAME_YIELD_GROUP_middle,0.002547,NAME_YIELD_GROUP_middle
CHANNEL_TYPE_Credit and cash offices,0.002536,CHANNEL_TYPE_Credit and cash offices
"CNT_PAYMENT_(4.0, 6.0]",0.002383,"CNT_PAYMENT_(4.0, 6.0]"
"CNT_PAYMENT_(14.0, 18.0]",0.002183,"CNT_PAYMENT_(14.0, 18.0]"
...,...,...
NAME_SELLER_INDUSTRY_Tourism,0.000016,NAME_SELLER_INDUSTRY_Tourism
NAME_CASH_LOAN_PURPOSE_Money for a third person,0.000015,NAME_CASH_LOAN_PURPOSE_Money for a third person
"RATE_INTEREST_PRIMARY_(0.1797, 0.18282]",0.000014,"RATE_INTEREST_PRIMARY_(0.1797, 0.18282]"
NAME_GOODS_CATEGORY_Additional Service,0.000014,NAME_GOODS_CATEGORY_Additional Service
NAME_CASH_LOAN_PURPOSE_Hobby,0.000014,NAME_CASH_LOAN_PURPOSE_Hobby
"RATE_INTEREST_PRIMARY_(0.14244, 0.14245]",0.000012,"RATE_INTEREST_PRIMARY_(0.14244, 0.14245]"
NAME_GOODS_CATEGORY_Fitness,0.000011,NAME_GOODS_CATEGORY_Fitness
"RATE_INTEREST_PRIVILEGED_(0.5, 0.569]",0.000011,"RATE_INTEREST_PRIVILEGED_(0.5, 0.569]"
"RATE_INTEREST_PRIMARY_(0.176, 0.17969]",0.000010,"RATE_INTEREST_PRIMARY_(0.176, 0.17969]"
"RATE_INTEREST_PRIMARY_(0.69619, 1.0]",0.000008,"RATE_INTEREST_PRIMARY_(0.69619, 1.0]"
"RATE_INTEREST_PRIMARY_(0.18282, 0.18283]",0.000007,"RATE_INTEREST_PRIMARY_(0.18282, 0.18283]"
"RATE_INTEREST_PRIMARY_(0.1969, 0.19691]",0.000007,"RATE_INTEREST_PRIMARY_(0.1969, 0.19691]"
"RATE_INTEREST_PRIMARY_(0.19691, 0.21097]",0.000007,"RATE_INTEREST_PRIMARY_(0.19691, 0.21097]"
NAME_CASH_LOAN_PURPOSE_Refusal to name the goal,0.000007,NAME_CASH_LOAN_PURPOSE_Refusal to name the goal
NAME_GOODS_CATEGORY_Education,0.000006,NAME_GOODS_CATEGORY_Education
"RATE_INTEREST_PRIMARY_(0.19333, 0.19334]",0.000006,"RATE_INTEREST_PRIMARY_(0.19333, 0.19334]"
"RATE_INTEREST_PRIMARY_(0.18914, 0.19316]",0.000006,"RATE_INTEREST_PRIMARY_(0.18914, 0.19316]"
NAME_PORTFOLIO_Cars,0.000006,NAME_PORTFOLIO_Cars
"RATE_INTEREST_PRIMARY_(0.12041, 0.14214]",0.000005,"RATE_INTEREST_PRIMARY_(0.12041, 0.14214]"
CHANNEL_TYPE_Car dealer,0.000004,CHANNEL_TYPE_Car dealer
"RATE_INTEREST_PRIMARY_(0.21097, 0.69591]",0.000004,"RATE_INTEREST_PRIMARY_(0.21097, 0.69591]"
"RATE_INTEREST_PRIMARY_(0.69591, 0.69619]",0.000003,"RATE_INTEREST_PRIMARY_(0.69591, 0.69619]"
"RATE_INTEREST_PRIMARY_(0.034771, 0.12041]",0.000003,"RATE_INTEREST_PRIMARY_(0.034771, 0.12041]"
"RATE_INTEREST_PRIVILEGED_(0.372, 0.5]",0.000002,"RATE_INTEREST_PRIVILEGED_(0.372, 0.5]"
AMT_CREDIT_nan,0.000002,AMT_CREDIT_nan
"RATE_INTEREST_PRIMARY_(0.17969, 0.1797]",0.000002,"RATE_INTEREST_PRIMARY_(0.17969, 0.1797]"
"RATE_INTEREST_PRIVILEGED_(0.716, 0.781]",0.000001,"RATE_INTEREST_PRIVILEGED_(0.716, 0.781]"
"RATE_INTEREST_PRIVILEGED_(0.867, 1.0]",0.000000,"RATE_INTEREST_PRIVILEGED_(0.867, 1.0]"
"RATE_INTEREST_PRIVILEGED_(0.835, 0.845]",0.000000,"RATE_INTEREST_PRIVILEGED_(0.835, 0.845]"
NAME_GOODS_CATEGORY_Animals,0.000000,NAME_GOODS_CATEGORY_Animals

In [226]:
import xgboost as xgb

booster_params = {'eta':0.05,
                  'gamma': 0.75,
                  'max_depth': 5,
                  'min_child_weight': 3,
                  'max_delta_step': 0,
                  'subsample': 0.85,
                  'colsample_bytree': 1,
                  'tree_method': 'auto',
                  'alpha': 0.25,
                  'lambda': 0.75}

def get_xgb_cv(params, top_k_features = 1):
    print(top_k_features)
    dtrain = xgb.DMatrix(data = X3.loc[:,list(sorted_features[:top_k_features].index)].values, label = y3.values,nthread= 6)
    xgb_cv = xgb.cv(params = booster_params , dtrain = dtrain, num_boost_round= 575, nfold = 3, stratified = True, metrics = 'auc', seed = 123,verbose_eval=0)
    result = xgb_cv.tail(1).assign(features = ' | '.join(sorted_features[:top_k_features].index), k = top_k_features)
    return(result)

ModuleNotFoundError: No module named 'xgboost'

In [ ]:
results = pd.concat([get_xgb_cv(booster_params, k) for k in range(1,10)])

In [223]:
ggplot(, aes(y = 'feature', x = 'fi')) + geom_point()

RuntimeError: Locator attempting to generate 1019 ticks from -45.5 to 972.5: exceeds Locator.MAXTICKS

In [35]:
meta = pd.read_csv(data_path + 'HomeCredit_columns_description.csv', encoding = 'latin1')

In [38]:
meta[meta.Table == 'previous_application.csv']

,Unnamed: 0,Table,Row,Description,Special
173,176,previous_application.csv,SK_ID_PREV,ID of previous credit in Home credit related t...,hashed
174,177,previous_application.csv,SK_ID_CURR,ID of loan in our sample,hashed
175,178,previous_application.csv,NAME_CONTRACT_TYPE,"Contract product type (Cash loan, consumer loa...",NaN
176,179,previous_application.csv,AMT_ANNUITY,Annuity of previous application,NaN
177,180,previous_application.csv,AMT_APPLICATION,For how much credit did client ask on the prev...,NaN
178,181,previous_application.csv,AMT_CREDIT,Final credit amount on the previous applicatio...,NaN
179,182,previous_application.csv,AMT_DOWN_PAYMENT,Down payment on the previous application,NaN
180,183,previous_application.csv,AMT_GOODS_PRICE,Goods price of good that client asked for (if ...,NaN
181,184,previous_application.csv,WEEKDAY_APPR_PROCESS_START,On which day of the week did the client apply ...,NaN
182,185,previous_application.csv,HOUR_APPR_PROCESS_START,Approximately at what day hour did the client ...,rounded
183,186,previous_application.csv,FLAG_LAST_APPL_PER_CONTRACT,Flag if it was last application for the previo...,NaN
184,187,previous_application.csv,NFLAG_LAST_APPL_IN_DAY,Flag if the application was the last applicati...,NaN
185,188,previous_application.csv,NFLAG_MICRO_CASH,Flag Micro finance loan,NaN
186,189,previous_application.csv,RATE_DOWN_PAYMENT,Down payment rate normalized on previous credit,normalized
187,190,previous_application.csv,RATE_INTEREST_PRIMARY,Interest rate normalized on previous credit,normalized
188,191,previous_application.csv,RATE_INTEREST_PRIVILEGED,Interest rate normalized on previous credit,normalized
189,192,previous_application.csv,NAME_CASH_LOAN_PURPOSE,Purpose of the cash loan,NaN
190,193,previous_application.csv,NAME_CONTRACT_STATUS,"Contract status (approved, cancelled, ...) of ...",NaN
191,194,previous_application.csv,DAYS_DECISION,Relative to current application when was the d...,time only relative to the application
192,195,previous_application.csv,NAME_PAYMENT_TYPE,Payment method that client chose to pay for th...,NaN
193,196,previous_application.csv,CODE_REJECT_REASON,Why was the previous application rejected,NaN
194,197,previous_application.csv,NAME_TYPE_SUITE,Who accompanied client when applying for the p...,NaN
195,198,previous_application.csv,NAME_CLIENT_TYPE,Was the client old or new client when applying...,NaN
196,199,previous_application.csv,NAME_GOODS_CATEGORY,What kind of goods did the client apply for in...,NaN
197,200,previous_application.csv,NAME_PORTFOLIO,"Was the previous application for CASH, POS, CA...",NaN
198,201,previous_application.csv,NAME_PRODUCT_TYPE,Was the previous application x-sell o walk-in,NaN
199,202,previous_application.csv,CHANNEL_TYPE,Through which channel we acquired the client o...,NaN
200,203,previous_application.csv,SELLERPLACE_AREA,Selling area of seller place of the previous a...,NaN
201,204,previous_application.csv,NAME_SELLER_INDUSTRY,The industry of the seller,NaN
202,205,previous_application.csv,CNT_PAYMENT,Term of previous credit at application of the ...,NaN
203,206,previous_application.csv,NAME_YIELD_GROUP,Grouped interest rate into small medium and hi...,grouped
204,207,previous_application.csv,PRODUCT_COMBINATION,Detailed product combination of the previous a...,NaN
205,208,previous_application.csv,DAYS_FIRST_DRAWING,Relative to application date of current applic...,time only relative to the application
206,209,previous_application.csv,DAYS_FIRST_DUE,Relative to application date of current applic...,time only relative to the application
207,210,previous_application.csv,DAYS_LAST_DUE_1ST_VERSION,Relative to application date of current applic...,time only relative to the application
208,211,previous_application.csv,DAYS_LAST_DUE,Relative to application date of current applic...,time only relative to the application
209,212,previous_application.csv,DAYS_TERMINATION,Relative to application date of current applic...,time only relative to the application
210,213,previous_application.csv,NFLAG_INSURED_ON_APPROVAL,Did the client requested insurance during the ...,NaN

In [ ]:
a.pivot_table(index = ['SK_ID_CURR',
])

In [ ]:
data_path = '/vol2/competitions/home-credit-default-risk/'

In [ ]:
data_files = os.listdir(data_path)
data_files

In [ ]:
df = pd.read_csv(data_path + 'application_train.csv.zip')

In [ ]:
df \
    .assign(INC_PER_MEMB = lambda x: x.AMT_INCOME_TOTAL / x.CNT_FAM_MEMBERS) \
    .groupby('TARGET') \
    .agg({'AMT_INCOME_TOTAL':['mean', 'median'],
          'AMT_CREDIT':['mean','std']})

In [ ]:
df.describe()

In [ ]:
from ggplot import ggplot, geom_boxplot, facet_wrap, geom_point, geom_histogram, geom_density, aes, geom_violin, scale_y_log, scale_x_log

In [ ]:
ggplot(df, aes(x = 'AMT_INCOME_TOTAL', y = 'DAYS_BIRTH', color = 'TARGET')) + geom_point(alpha = 0.3) + scale_x_log()

In [ ]:
import sklearn as sk

In [ ]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression

In [ ]:
def get_design_matrix(data, features, train_sample = 0.75):
    objects = data.columns[(data.dtypes == object)]
    objects = objects[objects.isin(features)]
        
    data = data[features + ['TARGET']]
        
    for o in objects:
        data = pd.concat([data, pd.get_dummies(data[o])], axis = 1)
        del data[o]                
    
    train_sample_idx = np.array([random.random() <= train_sample for i in range(data.shape[0])])
    X_train = data.loc[train_sample_idx].drop('TARGET', axis = 1)
    y_train = data.loc[train_sample_idx, 'TARGET']
    X_test = data.loc[~train_sample_idx].drop('TARGET', axis = 1)
    y_test = data.loc[~train_sample_idx, 'TARGET']
    
    return(X_train,y_train, X_test, y_test)

In [ ]:
flags = ['FLAG_MOBIL', 
         'FLAG_EMP_PHONE', 
         'FLAG_WORK_PHONE', 
         'FLAG_CONT_MOBILE', 
         'FLAG_PHONE', 
         'FLAG_EMAIL', 
         'REGION_RATING_CLIENT', 
         'REGION_RATING_CLIENT_W_CITY', 
         'FLAG_OWN_REALTY',
         'FLAG_OWN_CAR',
         'FLAG_DOCUMENT_2',
         'FLAG_DOCUMENT_3', 
         'FLAG_DOCUMENT_4',
         'FLAG_DOCUMENT_5']

features = ['AMT_INCOME_TOTAL', 
            'AMT_CREDIT', 
            'DAYS_BIRTH', 
            'DAYS_EMPLOYED', 
            'SK_ID_PREV', 
            'underpayment', 
            'utilization', 
            'payment_balance', 
            'SK_DPD', 
            'NAME_INCOME_TYPE',
            'ORGANIZATION_TYPE',
            'NAME_HOUSING_TYPE',
            'OCCUPATION_TYPE',
            'NAME_CONTRACT_TYPE',
            'NAME_FAMILY_STATUS',
            'NAME_TYPE_SUITE',
            'EXT_SOURCE_1', 
            'EXT_SOURCE_2',
            'EXT_SOURCE_3',
            'NAME_EDUCATION_TYPE',
            'NETBALANCE', 
            'AMT_INSTALMENT',
            'AMT_PAYMENT', 
            'DAYS_LAST_PHONE_CHANGE'] + flags + status_vars

In [ ]:
import json

In [ ]:
d = {}

In [ ]:
with open('features.json') as f:
    a = json.load(f)

In [ ]:
a['features']

In [ ]:
with open('options.json', 'wb') as f:
    json.dump(dict(set(features)), f)

In [ ]:
features

In [ ]:
X_train, y_train, X_test, y_test = get_design_matrix(df7, features, 0.65)

In [ ]:
from sklearn.metrics import roc_auc_score, classification_report, confusion_matrix
def get_model_performance(model, X_test, y_test):
    yhat = np.array([z[1] for z in model.predict_proba(X_test)])
#    print(classification_report(y_test, yhat))
#    print(confusion_matrix(y_test, yhat))
    auc = roc_auc_score(y_test, yhat)
#    print('\n' + 'AUC: ' + str(auc))
    return(auc)

In [ ]:
models =  [RandomForestClassifier(n_estimators = 100),
           GradientBoostingClassifier(n_estimators= 100),
           GradientBoostingClassifier(n_estimators= 300),
           GradientBoostingClassifier(n_estimators= 500),
           LogisticRegression()]
models = [m.fit(X_train, y_train) for m in models]

In [ ]:
model_performance = [get_model_performance(m, X_test, y_test) for m in models]
model_performance

In [ ]:
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import roc_curve, auc, make_scorer
from matplotlib import pyplot as plt
from sklearn.model_selection import validation_curve

In [ ]:
initial_parameters = {'max_depth': {'initial': 8, 'prange': range(8,14,2)},
                      'subsample': {'initial': 0.5, 'prange': [float(x)/100 for x in range(50,110,10)]},
                      'min_samples_split': {'initial': 500, 'prange': range(500,2500, 500)},
                      'min_samples_leaf': {'initial': 50, 'prange': range(20,100,10)},
                      'max_features': {'initial': 'sqrt', 'prange': ['sqrt', 'log2', None]},
                      'learning_rate': {'initial': 0.1, 'prange': [0.01, 0.05, 0.1, 0.2]}}

In [ ]:
initial_params = {}
param_grids = {}
for k in initial_parameters.keys():
    initial_params[k] = initial_parameters.get(k).get('initial')
    param_grids[k] = initial_parameters.get(k).get('prange')

In [ ]:
initial_params

In [ ]:
m = GradientBoostingClassifier(verbose = 0, n_estimators = 80)

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
grid_cv = GridSearchCV(estimator = m, param_grid = param_grids, scoring = 'roc_auc', cv = 3, n_jobs = 6, return_train_score=True)

In [ ]:
grid_cv.fit(X_train, y_train)

In [ ]:
grid_cv

In [ ]:
grid_cv

In [ ]:
print(1)

In [ ]:
grid_cv.grid_scores_

In [ ]:
# param_range = np.linspace(10, 2500, 10, dtype = int)
# param_range = [3,4,5,6,7,8,9,10,11,12,13,14,15]
# param_range = [float(x)/100 for x in range(50, 100, 10)]
param_range = []
train_scores, valid_scores = validation_curve(GradientBoostingClassifier(n_estimators = 50, max_depth = 11, subsample = 1, min_samples_split = 500, min_samples_leaf = 50, max_features = 'sqrt'), 
                                              X_train, y_train, "subsample", cv = 3, n_jobs = 6, verbose = 2,
                                              param_range = param_range, scoring = 'roc_auc')

In [ ]:
#Plot validation curve
train_scores_mean = np.mean(train_scores, axis=1)
train_scores_std = np.std(train_scores, axis=1)
test_scores_mean = np.mean(valid_scores, axis=1)
test_scores_std = np.std(valid_scores, axis=1)

plt.title("Validation Curve with GBM")
plt.xlabel("$\min_samples_split$")
plt.ylabel("Score")
plt.ylim(0.5, 1.1)
lw = 2
plt.fill_between(param_range, train_scores_mean - train_scores_std,
                 train_scores_mean + train_scores_std, alpha=0.2,
                 color="darkorange", lw=lw)
plt.fill_between(param_range, test_scores_mean - test_scores_std,
                 test_scores_mean + test_scores_std, alpha=0.2,
                 color="navy", lw=lw)
plt.legend(loc="best")
plt.show()

In [ ]:
test_scores_mean

In [ ]:
feature_importances = [dict(zip(X_train.columns, m.feature_importances_)) for m in models if hasattr(m, 'feature_importances_')]
feature_importances

In [ ]:
previous_application = pd.read_csv(data_path + 'previous_application.csv.zip')

In [ ]:
previous_application.groupby('SK_ID_CURR').RATE_DOWN_PAYMENT.mean().hist()

In [ ]:
df.columns

In [ ]:
previous_application['match'] = pd.Series([x in df.SK_ID_CURR.values for x in previous_application.SK_ID_CURR])

In [ ]:
df['has_previous_application'] = pd.Series([x in previous_application.SK_ID_CURR.values for x in df.SK_ID_CURR.values])

In [ ]:
# Simply having a history is a go
df.groupby('has_previous_application').agg({'TARGET': 'mean'})

In [ ]:
number_of_applications = previous_application[previous_application.match == True] \
    .groupby('SK_ID_CURR') \
    .agg({'SK_ID_PREV':'count'}) \
    .sort_values('SK_ID_PREV', ascending = False) \
    .reset_index()

number_of_applications.head()

In [ ]:
df2 = df.merge(number_of_applications, how = 'left', on = 'SK_ID_CURR')
df2.loc[pd.isnull(df2.SK_ID_PREV), 'SK_ID_PREV'] = 0

In [ ]:
installments_payments = pd.read_csv(data_path + 'installments_payments.csv.zip')
installments_payments.assign(nopay = lambda x:  x.AMT_PAYMENT < x.AMT_INSTALMENT).nopay.mean()

In [ ]:
underpayments = installments_payments.assign(underpayment = lambda x: x.AMT_PAYMENT < x.AMT_INSTALMENT).groupby('SK_ID_CURR').agg({'underpayment':'sum'}).reset_index()

In [ ]:
df3 = df2.merge(underpayments, how = 'left', on = 'SK_ID_CURR')
df3.loc[pd.isnull(df3.underpayment), 'underpayment'] = 0

In [ ]:
df3.groupby('TARGET').agg({'underpayment':'mean'})

In [ ]:
cc_balance = pd.read_csv(data_path + 'credit_card_balance.csv.zip')

In [ ]:
cc_util = cc_balance \
    .assign(utilization = lambda x: np.where(x.AMT_CREDIT_LIMIT_ACTUAL > 0, x.AMT_BALANCE / x.AMT_CREDIT_LIMIT_ACTUAL, 1),
            payment_balance = lambda x: np.where(x.AMT_BALANCE > 0, x.AMT_PAYMENT_TOTAL_CURRENT / x.AMT_BALANCE, 1)) \
    .groupby('SK_ID_CURR') \
    .agg({'utilization': 'mean', 'payment_balance': 'mean'}) \
    .reset_index()

In [ ]:
df4 = df3.merge(cc_util, how = 'left', on = 'SK_ID_CURR')
df4.loc[pd.isnull(df4.payment_balance), 'payment_balance'] = 0
df4.loc[pd.isnull(df4.utilization), 'utilization'] = 0

In [ ]:
cc_util[pd.isnull(cc_util.payment_balance)]

In [ ]:
bureau = pd.read_csv(data_path + 'bureau.csv.zip')
bureau_balance = pd.read_csv(data_path + 'bureau_balance.csv.zip')

In [ ]:
bureau_balance.STATUS.value_counts()

In [ ]:
bureau_balance.columns

In [ ]:
bureau_balance_statuses = bureau_balance \
    .groupby(['SK_ID_BUREAU', 'STATUS']) \
    .count() \
    .reset_index() \
    .pivot(index = 'SK_ID_BUREAU', columns = 'STATUS') \
    .fillna(0) \
    .reset_index('SK_ID_BUREAU')

In [ ]:
bureau_balance_statuses.columns = bureau_balance_statuses.columns.to_series().str.join('_')

In [ ]:
bureau_balance_statuses.head()

In [ ]:
bureau[bureau.SK_ID_BUREAU == 5001712]

In [ ]:
bureau_2 = bureau.merge(bureau_balance_statuses, how = 'left', left_on = 'SK_ID_BUREAU', right_on = 'SK_ID_BUREAU_')

In [ ]:
bureau_2[bureau_2.SK_ID_BUREAU == 5001712]

In [ ]:
len(bureau_2[pd.isnull(bureau_2.MONTHS_BALANCE_0)])

In [ ]:
len(bureau_2)

In [ ]:
bureau_3

In [ ]:
df5 = df4.merge(bureau_3, how = 'left', on = 'SK_ID_CURR').fillna(0)

In [ ]:
df5

In [ ]:
data_files

In [ ]:
POS_CASH = pd.read_csv(data_path + 'POS_CASH_balance.csv.zip')

In [ ]:
POS_CASH.head()

In [ ]:
POS_CASH.describe()

In [ ]:
meta = pd.read_csv(data_path + 'HomeCredit_columns_description.csv', encoding = 'latin1')

In [ ]:
meta[meta.Table == 'POS_CASH_balance.csv']

In [ ]:
meta.head(100)

In [ ]:
DaysPastDue

In [ ]:
DaysPastDue = POS_CASH.groupby('SK_ID_CURR').SK_DPD.mean().reset_index()

In [ ]:
df6 = df5.merge(DaysPastDue, how = 'left', on = 'SK_ID_CURR').fillna(0)

In [ ]:
df6

In [ ]:
data_files

In [ ]:
pprint(list(df.columns))

In [ ]:
df.EXT_SOURCE_1.value_counts()

In [ ]:
print(df.groupby('TARGET').mean().transpose())

In [ ]:
objects = list(df.columns[df.dtypes == object])

In [ ]:
objects

In [ ]:
for c in objects:
    print(df.groupby(c).TARGET.mean())

In [ ]:
installments_balance = installments_payments.groupby('SK_ID_CURR')['AMT_INSTALMENT', 'AMT_PAYMENT'].sum().reset_index().assign(NETBALANCE = lambda x: x.AMT_PAYMENT - x.AMT_INSTALMENT )

In [ ]:
df7 = df6.merge(installments_balance, how = 'left', on = 'SK_ID_CURR')
df7.loc[pd.isnull(df7.NETBALANCE), ['AMT_PAYMENT', 'AMT_INSTALMENT', 'NETBALANCE']] = 0

In [ ]:
df7.NETBALANCE.describe()

In [ ]:
list(df7.columns)

In [ ]:
a = meta.iterrows()

In [ ]:
next(a)

In [ ]:
df[df.TARGET == 0].DAYS_LAST_PHONE_CHANGE.values

In [ ]:
ttest_ind()

In [ ]:
ttest_ind(df[df.TARGET == 0].DAYS_LAST_PHONE_CHANGE.values,
          df[df.TARGET == 1].DAYS_LAST_PHONE_CHANGE.values, equal_var = False, nan_policy = 'omit')

In [ ]:
from scipy.stats import ttest_ind
df.groupby('TARGET').DAYS_LAST_PHONE_CHANGE.agg(lambda x: x.mean()/x.std())

In [ ]:
print(meta[meta.Table == 'application_{train|test}.csv'].head(100).to_string())

In [ ]:
print(meta[meta.Row == 'FLOORSMAX_MEDI'].Description.to_string()[4])