In [2]:
import pandas as pd

In [8]:
clicks_train = pd.read_csv('clicks_train.csv')

In [9]:
clicks_test = pd.read_csv('clicks_test.csv')

In [26]:
clicks_test.head(5)

   display_id   ad_id
0    16874594   66758
1    16874594  150083
2    16874594  162754
3    16874594  170392
4    16874594  172888

In [33]:
events.head()

,display_id,uuid,document_id,timestamp,platform,geo_location,test
0,1,cb8c55702adb93,379743,61,3,US>SC>519,False
1,2,79a85fa78311b9,1794259,81,2,US>CA>807,False
2,3,822932ce3d8757,1179111,182,2,US>MI>505,False
3,4,85281d0a49f7ac,1777797,234,2,US>WV>564,False
4,5,8d0daef4bf5b56,252458,338,2,SG>00,False

In [13]:
clicks_train.display_id.max()

16874593

In [3]:
events = pd.read_csv('events.csv')

/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [15]:
events['test'] = events.display_id >16874593

In [28]:
page_views = pd.read_csv('page_views.csv',chunksize=1000)

In [29]:
tmp = page_views.get_chunk()

In [31]:
promoted_content = pd.read_csv('promoted_content.csv')

In [35]:
clicks_train.groupby('ad_id')['clicked'].mean()

ad_id
1         0.000000
2         0.045455
3         0.068323
4         0.125000
5         0.000000
6         0.000000
7         0.289196
8         0.142857
9         0.000000
10        0.111111
11        0.000000
12        0.166667
13        0.125000
14        0.100000
15        0.000000
16        0.333333
17        0.100000
18        0.000000
20        0.000000
21        0.000000
22        0.000000
23        0.181818
24        0.000000
25        0.000000
26        0.045455
27        0.000000
28        0.000000
29        0.000000
30        0.000000
31        0.166667
            ...
547501    0.000000
547504    0.000000
547505    0.000000
547509    0.000000
547513    0.000000
547522    0.125000
547548    0.750000
547552    0.000000
547554    0.000000
547561    0.000000
547562    0.000000
547572    0.000000
547573    0.000000
547576    0.000000
547581    0.000000
547582    0.222222
547584    0.000000
547585    0.000000
547586    1.000000
547592    0.000000
547625    0.000000
547678    0.000000
547812    1.000000
547864    0.000000
547865    0.000000
547866    0.250000
547875    0.000000
547879    0.000000
547924    0.000000
548019    1.000000
Name: clicked, dtype: float64

In [27]:
events.head(5)

,display_id,uuid,document_id,timestamp,platform,geo_location,test
0,1,cb8c55702adb93,379743,61,3,US>SC>519,False
1,2,79a85fa78311b9,1794259,81,2,US>CA>807,False
2,3,822932ce3d8757,1179111,182,2,US>MI>505,False
3,4,85281d0a49f7ac,1777797,234,2,US>WV>564,False
4,5,8d0daef4bf5b56,252458,338,2,SG>00,False

In [25]:
events.uuid.value_counts().median()

1.0

In [36]:
events.dtypes

display_id       int64
uuid            object
document_id      int64
timestamp        int64
platform        object
geo_location    object
test              bool
dtype: object

In [7]:
events.document_id.value_counts()

1179111    319203
394689     208574
1827718    195070
38922       86380
1788295     68509
2102553     67229
7054        66240
1060089     53369
1690147     49215
38915       47918
1493650     44134
2150689     42671
1448387     40213
1316528     37172
1535449     35074
467462      34570
1717049     33816
1108855     33583
1666933     32148
1271578     31970
1077294     31901
1980824     29804
1026091     28754
2165306     28103
1280592     27494
1198481     26596
1178289     26248
427953      26025
357569      25697
1027695     23972
            ...
1978294         1
234693          1
185581          1
1634158         1
955749          1
1686909         1
175137          1
2150573         1
1797913         1
2183325         1
1381908         1
1437385         1
1316404         1
1568393         1
1545796         1
1513044         1
1529436         1
1136284         1
1076857         1
1283780         1
1218276         1
1234668         1
1201916         1
2603154         1
2021228         1
1824716         1
1791964         1
2461701         1
814585          1
318766          1
Name: document_id, dtype: int64

In [37]:
clicks_train.head()

   display_id   ad_id  clicked
0           1   42337        0
1           1  139684        0
2           1  144739        1
3           1  156824        0
4           1  279295        0

In [41]:
len(clicks_train.ad_id.value_counts())

478950

Let's get historical concordance of contexts and ads clicked
using clicks_train

In [44]:
clicks_train.groupby('display_id')['ad_id','clicked'].pipe(lambda x: )

In [45]:
clicks_train_smp = clicks_train.head(500)

In [66]:
clicks_concord = clicks_train_smp.pivot(index = 'display_id', columns='ad_id',values='clicked')

In [69]:
clicks_concord

ad_id,3685,5116,5292,5558,5760,7432,8386,8748,10731,13030,...,330189,330981,331260,331466,332908,333491,333874,334742,335983,340041
display_id,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [70]:
clicks_concord.columns = ['ad_' + str(c) for c in clicks_concord.columns]

In [80]:
import math

In [91]:
clicks_concord.query('ad_5116 == ad_5116').filter(axis = 0, items = [0,1])

Empty DataFrame
Columns: [ad_3685, ad_5116, ad_5292, ad_5558, ad_5760, ad_7432, ad_8386, ad_8748, ad_10731, ad_13030, ad_14081, ad_14096, ad_17917, ad_18493, ad_19959, ad_20801, ad_22414, ad_23324, ad_23522, ad_25289, ad_26724, ad_26894, ad_27309, ad_28337, ad_28347, ad_29046, ad_29281, ad_31367, ad_31770, ad_32481, ad_34348, ad_35316, ad_35982, ad_36619, ad_37099, ad_37191, ad_37416, ad_39487, ad_39872, ad_40397, ad_40529, ad_41584, ad_42337, ad_43517, ad_44927, ad_45024, ad_45196, ad_46128, ad_47081, ad_47902, ad_47949, ad_48185, ad_50452, ad_50640, ad_51402, ad_51445, ad_51955, ad_52086, ad_52574, ad_52838, ad_54049, ad_54154, ad_54606, ad_55167, ad_55518, ad_55988, ad_56754, ad_57971, ad_59519, ad_59628, ad_61159, ad_64255, ad_65278, ad_66921, ad_66942, ad_67305, ad_67861, ad_68291, ad_68305, ad_69340, ad_69823, ad_70153, ad_71547, ad_73754, ad_74623, ad_75426, ad_77848, ad_78297, ad_79784, ad_79828, ad_80301, ad_81009, ad_81652, ad_81657, ad_84937, ad_85397, ad_86281, ad_86683, ad_87029, ad_88711, ...]
Index: []

[0 rows x 447 columns]

In [64]:
clicks_concord.columns

Int64Index([  3685,   5116,   5292,   5558,   5760,   7432,   8386,   8748,
             10731,  13030,
            ...
            330189, 330981, 331260, 331466, 332908, 333491, 333874, 334742,
            335983, 340041],
           dtype='int64', name=u'ad_id', length=447)